# See http://about.travis-ci.org/docs/user/build-configuration/
sudo: false

before_script:
  - export MAVEN_SKIP_RC=true

script:
  - export MAVEN_OPTS="-Xmx2469m -XX:MaxPermSize=512m"
  - build/travis_build.sh
